### ISSUE TITLE
修复 package-local task workspace 忽略 worktree 配置的路径回归

### ISSUE THREAD

**Issue by wesleywu** [castbox/guru-trellis#212]
## 背景

Issue #195 / PR #210 将 `guru-create-task-workspace` 迁移到 package-local runtime，并要求保持迁移前的现有行为合同。迁移后的 Skill 合同和配置模板仍规定：

- `workspace_mode: worktree` 时从 configured worktree root 创建任务 worktree；
- `worktree_root: ""` 默认解析为 `../<repo-name>-worktrees`；
- checker 从 current config、reviewed workspace slug 与 live Git facts 推导绝对路径。

但当前 `main@8d52f2b5bfa64c29a64deb616e9f5b4a7c4ebce8` 的 package-local executor 与 checker 都直接使用 `repo.parent / workspace_slug`，完全绕过 `workspace_mode` 和 `worktree_root` 配置。

以 `guru-trellis` 和 workspace slug `211-task-commit-hooks` 为例，合同期望路径是：

```text
/Users/wumengye/Documents/GoProjects/guru-trellis-worktrees/211-task-commit-hooks
```

当前 executor 实际推导为：

```text
/Users/wumengye/Documents/GoProjects/211-task-commit-hooks
```

这是 #195 引入的独立行为回归，与 Issue #211 的 task commit hooks 修复无关。#211 可以独立继续；本 Issue 不处理、移动或清理任何已经创建的 #211 worktree、branch、task 或 runtime mapping。

## 当前证据

- 配置合同：`trellis/workflows/guru-team/config-template.yml` 第 39-44 行，空 `worktree_root` 表示 `../<repo-name>-worktrees`。
- Skill 合同：`trellis/skills/guru-team/packages/guru-create-task-workspace/references/contract.md` 第 28-31 行，要求读取 configured worktree-root 后确定 workspace object。
- Workflow README：`trellis/workflows/guru-team/README.md` 第 633-634 行，声明 checker 从 current config、reviewed slug 和 live Git facts 推导 worktree。
- Preset README：`trellis/presets/guru-team/README.md` 第 964-966 行，声明相同推导规则。
- 当前 executor：`trellis/skills/guru-team/packages/guru-create-task-workspace/runtime/execute.py` 第 27 行使用 `repo.parent / workspace_slug`。
- 当前 checker：`trellis/skills/guru-team/packages/guru-create-task-workspace/runtime/check.py` 第 19 行使用相同错误推导。
- #195 前的 `7e0eb94` 使用 `configured_worktree_root(root, config) / workspace_slug`，其中空配置返回 `root.parent / f"{root.name}-worktrees"`，相对配置基于 repository root 解析，绝对配置直接使用。
- 当前 package test 在临时 repo 的同级目录接受 `repo.parent / workspace_slug`，没有加载或断言真实 workspace config，因此未拦截迁移回归。
- Live duplicate search 未发现覆盖该 current regression 的开放 Issue；#152 负责新增 warm worktree pool mode，不拥有既有 `worktree/current` 配置语义的恢复。

## 目标

恢复 `guru-create-task-workspace` package-local runtime 对现行 workspace 配置合同的完整支持，使语义计划、executor、checker、runtime mapping 和 installed copy 对同一绝对 workspace identity 保持一致。

### 1. 统一 workspace 路径解析

- `workspace_mode: worktree` 且 `worktree_root` 为空时，目标根目录必须为 `../<repo-name>-worktrees`。
- 显式绝对 `worktree_root` 必须原样作为根目录使用。
- 显式相对 `worktree_root` 必须按现有合同相对 repository root 解析并规范化。
- `workspace_mode: current` 必须使用当前 repository checkout，不得创建同级 worktree。
- 缺失或不支持的 mode、不可接受的路径及既有冲突必须按现有错误合同 fail closed。

### 2. 单一确定性推导

- planner/recorder、executor、checker 和 recovery/reuse 路径必须使用同一配置解析语义，不得分别硬编码路径。
- public result 继续不暴露 machine-local absolute workspace path；checker 应从 current config、reviewed slug 和 live Git facts重新推导。
- ignored runtime mapping 中的 `workspace_path` 必须与实际创建或复用的 workspace 完全一致。
- 不得把 machine-local 路径加入 tracked task artifact 或 public handoff DTO。

### 3. 保持现有 Skill 边界

- 修复 owner 保持在 `trellis/skills/guru-team/packages/guru-create-task-workspace/`；不得恢复共享 `guru_team_trellis.py` 单体或 compatibility fallback。
- AI 继续拥有命名、scope、充分性、冲突分类和副作用确认；runtime 只解析配置并执行/校验确定性事实。
- 保持 stable Skill id、typed exits、consumer projection、confirmation lifecycle 和 public schema，除非 fresh implementation 证明需要单独迁移。
- 不新增 pooled workspace mode；Issue #152 继续独立拥有该能力。

### 4. Canonical、installed 与升级一致性

- 同步 canonical package、dogfood installed package、shared/Codex/Claude/Cursor projections、preset manifest 和直接相关文档。
- 验证 clean initial install、existing repo preset reapply 和 official Trellis update 后配置路径行为仍一致。
- 不依赖对当前 dogfood installed copy 的一次性 patch，不留下未处理 `.new`、`.bak` 或 conflict sidecar。

## 验收标准

- [ ] 默认空 `worktree_root` 的真实 Git 测试证明 `<repo-parent>/<repo-name>-worktrees/<workspace-slug>` 被创建并通过 checker。
- [ ] 显式绝对 `worktree_root` 的创建、reuse/conflict 和 checker 路径一致。
- [ ] 显式相对 `worktree_root` 相对 repository root 解析，executor/checker/runtime mapping 一致。
- [ ] `workspace_mode: current` 不创建 worktree，并在当前 checkout 上遵守 task artifact 与 workspace boundary 合同。
- [ ] invalid mode、路径冲突和 stale/mismatch 正常路径 fail closed，且不会部分创建 branch、worktree、task 或 mapping。
- [ ] 测试不再以 `repo.parent / workspace_slug` 作为无配置的隐式期望，而是显式加载并断言配置合同。
- [ ] package-local tests、canonical/installed parity、source/installed validators、dogfood drift 和 `git diff --check` 通过。
- [ ] clean throwaway initial install、existing repo update/reapply 和 official Trellis update 后上述矩阵通过，且无未处理 sidecar。
- [ ] Independent current-HEAD Branch Review 无未关闭 P0-P3 finding。

## 非目标

- 不修改或吸收 Issue #211 的 commit hook scope。
- 不移动、删除、重建或清理现存的 #211 worktree、branch、task 或 runtime mapping。
- 不实现 Issue #152 的 warm worktree pool。
- 不修改 Trellis upstream、全局 npm 包或 `node_modules`。
- 不扩展到恶意输入、并发竞态、锁、额外 crash consistency 或跨 OS 原子性。

## 关联

- Regression from #195 / PR #210.
- Restores the pre-migration `guru-create-task-workspace` configured-root behavior.
- Related to #152 only as a distinct future workspace mode; this Issue does not implement or close it.
- Independent of #211.
